// <auto-generated />
using DieselCarDataAccess.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace DieselCarDataAccess.Migrations
{
    [DbContext(typeof(DieselCarDbContext))]
    [Migration("20200609131445_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("DieselCarDataAccess.Database.DieselCarTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("CarBrand")
                        .HasColumnName("CARBRAND");

                    b.Property<string>("CarModel")
                        .HasColumnName("CARMODEL");

                    b.HasKey("Id");

                    b.ToTable("DIESELCAR");
                });
#pragma warning restore 612, 618
        }
    }
}
