apiVersion: apps/v1 
kind: Deployment
metadata:
  name: carms-app
spec:
  replicas: 1
  selector:
    matchLabels:
       name: car-app
  template:
    metadata:
      name: car-app
      labels:
        name: car-app 
    spec: 
      containers:
       - name: car-app
         image: carms:dev-1.0.0 
